name: Docker Hub Push

on:
  push:
    branches:
      - dockerhub

jobs:
  docker_hub_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-strapi-image2 . 
      
    - name: Tag Docker image
      run: docker tag my-strapi-image2 adamsia/test-strapi:my-strapi-image2
    
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.ADAMDOCKHERHUB_USERNAME }} -p ${{ secrets.ADAMDOCKERHUB_PASSWORD }}

    - name: Push Docker Image
      run: docker push adamsia/test-strapi:my-strapi-image2
