name: Docker Hub Push

on:
  push:
    branches:
      - dockerhub

jobs:
  docker_hub_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Build Docker Image
      run: docker build -t my-strapi-image:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: adamsia
        password: "@Adam1971"

    - name: Push Docker Image
      run: docker push adamsia/test-strapi:latest 
