name: Docker Hub Push

on:
  push:
    branches:
      - dockerhub

jobs:
  docker_hub_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Build Docker Image
      run: docker build -t my-strapi-image . # Replace 'my-strapi-image' with your desired image name
    
    - name: Log in to Docker Hub
      run: docker login -u ${{ adamsia }} -p ${{ @Adam1971 }}
    
    - name: Push Docker Image
      run: docker push adamsia/test-strapi:my-strapi-image # Replace 'my-strapi-image' with your desired image name
